/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 6002754
 */
public class VentanaMain extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMain
     */
    public VentanaMain() {
        initComponents();
        lMPlusPartidoGanado.setVisible(false);
        tMPlusPartidoGanado.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgCargoDirectivo = new javax.swing.ButtonGroup();
        bgPosicion = new javax.swing.ButtonGroup();
        tpGeneral = new javax.swing.JTabbedPane();
        pJugadores = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tJDNI = new javax.swing.JTextField();
        tJNombre = new javax.swing.JTextField();
        tJTelefono = new javax.swing.JTextField();
        tJDireccion = new javax.swing.JTextField();
        tJPGanados = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tJSueldo = new javax.swing.JTextField();
        bPortero = new javax.swing.JRadioButton();
        bDefensa = new javax.swing.JRadioButton();
        bDelantero = new javax.swing.JRadioButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        tJFechaNacimiento = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        tJPlusPartidoGanado = new javax.swing.JTextField();
        tJNumeroGoles = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        tJPlusPorGol = new javax.swing.JTextField();
        tpEntrenadores = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tEDNI = new javax.swing.JTextField();
        tENombre = new javax.swing.JTextField();
        tETelefono = new javax.swing.JTextField();
        tEDireccion = new javax.swing.JTextField();
        tEPGanados = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tESueldo = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        tEPlusPartidoGanado = new javax.swing.JTextField();
        tEPlusPartidoGanado1 = new javax.swing.JTextField();
        pMantenedores = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tMDNI = new javax.swing.JTextField();
        tMNombre = new javax.swing.JTextField();
        tMTelefono = new javax.swing.JTextField();
        tMDireccion = new javax.swing.JTextField();
        tMPGanados = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tMSueldo = new javax.swing.JTextField();
        lMPlusPartidoGanado = new javax.swing.JLabel();
        tMPlusPartidoGanado = new javax.swing.JTextField();
        cMFijo = new javax.swing.JCheckBox();
        pDirectivos = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        tDDNI = new javax.swing.JTextField();
        tDNombre = new javax.swing.JTextField();
        tDTelefono = new javax.swing.JTextField();
        tDDireccion = new javax.swing.JTextField();
        tDPGanados = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        tDSueldo = new javax.swing.JTextField();
        bDelegado = new javax.swing.JRadioButton();
        bPresidente = new javax.swing.JRadioButton();
        bSecretario = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        cDActivo = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre:");

        jLabel2.setText("DNI:");

        jLabel3.setText("Dirección:");

        jLabel4.setText("Teléfono");

        jLabel5.setText("P. Ganados:");

        tJDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tJDNIActionPerformed(evt);
            }
        });

        tJNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tJNombreActionPerformed(evt);
            }
        });

        tJTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tJTelefonoActionPerformed(evt);
            }
        });

        tJDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tJDireccionActionPerformed(evt);
            }
        });

        tJPGanados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tJPGanadosActionPerformed(evt);
            }
        });

        jLabel6.setText("Sueldo:");

        tJSueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tJSueldoActionPerformed(evt);
            }
        });

        bgPosicion.add(bPortero);
        bPortero.setText("Presidente");

        bgPosicion.add(bDefensa);
        bDefensa.setText("Delegado");

        bgPosicion.add(bDelantero);
        bDelantero.setText("Secretario");

        jLabel27.setText("Posición:");

        jLabel28.setText("Fecha Nacimiento:");

        tJFechaNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tJFechaNacimientoActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel29.setText("Plus Partido Ganado:");

        tJPlusPartidoGanado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tJPlusPartidoGanadoActionPerformed(evt);
            }
        });

        tJNumeroGoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tJNumeroGolesActionPerformed(evt);
            }
        });

        jLabel30.setText("Nº Goles:");

        jLabel31.setText("Plus por Gol:");

        tJPlusPorGol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tJPlusPorGolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pJugadoresLayout = new javax.swing.GroupLayout(pJugadores);
        pJugadores.setLayout(pJugadoresLayout);
        pJugadoresLayout.setHorizontalGroup(
            pJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pJugadoresLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addGroup(pJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(18, 18, 18)
                .addGroup(pJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pJugadoresLayout.createSequentialGroup()
                        .addComponent(tJPGanados, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(tJSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pJugadoresLayout.createSequentialGroup()
                        .addGroup(pJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pJugadoresLayout.createSequentialGroup()
                                .addGroup(pJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tJNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tJDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tJDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bPortero)
                                    .addComponent(bDefensa)
                                    .addComponent(bDelantero))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pJugadoresLayout.createSequentialGroup()
                                .addComponent(tJTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(181, 181, 181)))
                        .addGroup(pJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pJugadoresLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tJFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pJugadoresLayout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tJPlusPartidoGanado, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pJugadoresLayout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tJPlusPorGol, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pJugadoresLayout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tJNumeroGoles, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pJugadoresLayout.setVerticalGroup(
            pJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pJugadoresLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(pJugadoresLayout.createSequentialGroup()
                            .addGroup(pJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pJugadoresLayout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addGroup(pJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pJugadoresLayout.createSequentialGroup()
                                            .addGap(14, 14, 14)
                                            .addComponent(bDefensa)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(bDelantero))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pJugadoresLayout.createSequentialGroup()
                                            .addGap(63, 63, 63)
                                            .addComponent(tJDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pJugadoresLayout.createSequentialGroup()
                                    .addGroup(pJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bPortero)
                                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tJFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(pJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tJNumeroGoles, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(pJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tJPlusPorGol, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGroup(pJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pJugadoresLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tJTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pJugadoresLayout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addGroup(pJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tJPlusPartidoGanado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(pJugadoresLayout.createSequentialGroup()
                            .addGroup(pJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tJNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(pJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tJDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tJPGanados, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tJSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        tpGeneral.addTab("Jugadores", pJugadores);

        jLabel7.setText("Nombre:");

        jLabel8.setText("DNI:");

        jLabel9.setText("Dirección:");

        jLabel10.setText("Teléfono");

        jLabel11.setText("P. Ganados:");

        tEDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tEDNIActionPerformed(evt);
            }
        });

        tENombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tENombreActionPerformed(evt);
            }
        });

        tETelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tETelefonoActionPerformed(evt);
            }
        });

        tEDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tEDireccionActionPerformed(evt);
            }
        });

        tEPGanados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tEPGanadosActionPerformed(evt);
            }
        });

        jLabel12.setText("Sueldo:");

        tESueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tESueldoActionPerformed(evt);
            }
        });

        jLabel26.setText("Plus partido ganado:");

        tEPlusPartidoGanado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tEPlusPartidoGanadoActionPerformed(evt);
            }
        });

        tEPlusPartidoGanado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tEPlusPartidoGanado1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tpEntrenadoresLayout = new javax.swing.GroupLayout(tpEntrenadores);
        tpEntrenadores.setLayout(tpEntrenadoresLayout);
        tpEntrenadoresLayout.setHorizontalGroup(
            tpEntrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
            .addGroup(tpEntrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tpEntrenadoresLayout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addGroup(tpEntrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11)
                        .addGroup(tpEntrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGap(18, 18, 18)
                    .addGroup(tpEntrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tENombre, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tEDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tETelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(tpEntrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tpEntrenadoresLayout.createSequentialGroup()
                                .addComponent(tEDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel26)
                                .addGap(18, 18, 18)
                                .addComponent(tEPlusPartidoGanado, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tpEntrenadoresLayout.createSequentialGroup()
                                .addComponent(tEPGanados, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(130, 130, 130)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(tESueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(29, Short.MAX_VALUE)))
            .addGroup(tpEntrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tpEntrenadoresLayout.createSequentialGroup()
                    .addContainerGap(500, Short.MAX_VALUE)
                    .addComponent(tEPlusPartidoGanado1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(19, 19, 19)))
        );
        tpEntrenadoresLayout.setVerticalGroup(
            tpEntrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 245, Short.MAX_VALUE)
            .addGroup(tpEntrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tpEntrenadoresLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addGroup(tpEntrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(tpEntrenadoresLayout.createSequentialGroup()
                            .addGroup(tpEntrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tENombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(tpEntrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tEDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(tpEntrenadoresLayout.createSequentialGroup()
                            .addGroup(tpEntrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tEDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tEPlusPartidoGanado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tETelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(tpEntrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tEPGanados, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tESueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(16, Short.MAX_VALUE)))
            .addGroup(tpEntrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tpEntrenadoresLayout.createSequentialGroup()
                    .addContainerGap(119, Short.MAX_VALUE)
                    .addComponent(tEPlusPartidoGanado1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(94, 94, 94)))
        );

        tpGeneral.addTab("Entrenadores", tpEntrenadores);

        jLabel13.setText("Nombre:");

        jLabel14.setText("DNI:");

        jLabel15.setText("Dirección:");

        jLabel16.setText("Teléfono");

        jLabel17.setText("P. Ganados:");

        tMDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tMDNIActionPerformed(evt);
            }
        });

        tMNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tMNombreActionPerformed(evt);
            }
        });

        tMTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tMTelefonoActionPerformed(evt);
            }
        });

        tMDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tMDireccionActionPerformed(evt);
            }
        });

        tMPGanados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tMPGanadosActionPerformed(evt);
            }
        });

        jLabel18.setText("Sueldo:");

        tMSueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tMSueldoActionPerformed(evt);
            }
        });

        lMPlusPartidoGanado.setText("Plus partido ganado:");

        tMPlusPartidoGanado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tMPlusPartidoGanadoActionPerformed(evt);
            }
        });

        cMFijo.setText("Fijo");

        javax.swing.GroupLayout pMantenedoresLayout = new javax.swing.GroupLayout(pMantenedores);
        pMantenedores.setLayout(pMantenedoresLayout);
        pMantenedoresLayout.setHorizontalGroup(
            pMantenedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMantenedoresLayout.createSequentialGroup()
                .addContainerGap(490, Short.MAX_VALUE)
                .addComponent(cMFijo)
                .addGap(177, 177, 177))
            .addGroup(pMantenedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pMantenedoresLayout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addGroup(pMantenedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel16)
                        .addComponent(jLabel17)
                        .addGroup(pMantenedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGap(18, 18, 18)
                    .addGroup(pMantenedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tMNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tMDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tMTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pMantenedoresLayout.createSequentialGroup()
                            .addGroup(pMantenedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tMPGanados, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tMDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(59, 59, 59)
                            .addGroup(pMantenedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pMantenedoresLayout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addGap(18, 18, 18)
                                    .addComponent(tMSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pMantenedoresLayout.createSequentialGroup()
                                    .addComponent(lMPlusPartidoGanado)
                                    .addGap(18, 18, 18)
                                    .addComponent(tMPlusPartidoGanado, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addContainerGap(29, Short.MAX_VALUE)))
        );
        pMantenedoresLayout.setVerticalGroup(
            pMantenedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMantenedoresLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(cMFijo)
                .addContainerGap(198, Short.MAX_VALUE))
            .addGroup(pMantenedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pMantenedoresLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addGroup(pMantenedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pMantenedoresLayout.createSequentialGroup()
                            .addGroup(pMantenedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tMNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(pMantenedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tMDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pMantenedoresLayout.createSequentialGroup()
                            .addGroup(pMantenedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tMDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lMPlusPartidoGanado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tMPlusPartidoGanado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tMTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(pMantenedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tMPGanados, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tMSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(16, Short.MAX_VALUE)))
        );

        tpGeneral.addTab("Mantenedores", pMantenedores);

        jLabel19.setText("Nombre:");

        jLabel20.setText("DNI:");

        jLabel21.setText("Dirección:");

        jLabel22.setText("Teléfono");

        jLabel23.setText("P. Ganados:");

        tDDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDDNIActionPerformed(evt);
            }
        });

        tDNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDNombreActionPerformed(evt);
            }
        });

        tDTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDTelefonoActionPerformed(evt);
            }
        });

        tDDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDDireccionActionPerformed(evt);
            }
        });

        tDPGanados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDPGanadosActionPerformed(evt);
            }
        });

        jLabel24.setText("Sueldo:");

        tDSueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDSueldoActionPerformed(evt);
            }
        });

        bgCargoDirectivo.add(bDelegado);
        bDelegado.setText("Delegado");

        bgCargoDirectivo.add(bPresidente);
        bPresidente.setText("Presidente");

        bgCargoDirectivo.add(bSecretario);
        bSecretario.setText("Secretario");

        jLabel25.setText("Nombre:");

        cDActivo.setText("Activo");
        cDActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cDActivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pDirectivosLayout = new javax.swing.GroupLayout(pDirectivos);
        pDirectivos.setLayout(pDirectivosLayout);
        pDirectivosLayout.setHorizontalGroup(
            pDirectivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
            .addGroup(pDirectivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pDirectivosLayout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addGroup(pDirectivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel22)
                        .addComponent(jLabel23)
                        .addGroup(pDirectivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGap(18, 18, 18)
                    .addGroup(pDirectivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pDirectivosLayout.createSequentialGroup()
                            .addGroup(pDirectivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tDPGanados, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tDNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(123, 123, 123)
                            .addGroup(pDirectivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel24)
                                .addComponent(jLabel25)))
                        .addComponent(tDDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tDDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tDTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(pDirectivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cDActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tDSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bDelegado, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bPresidente, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bSecretario, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(29, Short.MAX_VALUE)))
        );
        pDirectivosLayout.setVerticalGroup(
            pDirectivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 245, Short.MAX_VALUE)
            .addGroup(pDirectivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pDirectivosLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addGroup(pDirectivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pDirectivosLayout.createSequentialGroup()
                            .addComponent(tDDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tDTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pDirectivosLayout.createSequentialGroup()
                            .addGroup(pDirectivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tDNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(pDirectivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tDDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pDirectivosLayout.createSequentialGroup()
                            .addComponent(bPresidente)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bDelegado)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bSecretario)
                            .addGap(29, 29, 29)
                            .addComponent(cDActivo)
                            .addGap(20, 20, 20)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(pDirectivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tDPGanados, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tDSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(16, Short.MAX_VALUE)))
        );

        tpGeneral.addTab("Directivos", pDirectivos);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jMenu1.setText("Archivo");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("E / S Archivos");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Salir");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(tpGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tJDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tJDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tJDNIActionPerformed

    private void tJNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tJNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tJNombreActionPerformed

    private void tJTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tJTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tJTelefonoActionPerformed

    private void tJDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tJDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tJDireccionActionPerformed

    private void tJPGanadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tJPGanadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tJPGanadosActionPerformed

    private void tJSueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tJSueldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tJSueldoActionPerformed

    private void tEDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tEDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tEDNIActionPerformed

    private void tENombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tENombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tENombreActionPerformed

    private void tETelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tETelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tETelefonoActionPerformed

    private void tEDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tEDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tEDireccionActionPerformed

    private void tEPGanadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tEPGanadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tEPGanadosActionPerformed

    private void tESueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tESueldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tESueldoActionPerformed

    private void tMDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tMDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tMDNIActionPerformed

    private void tMNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tMNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tMNombreActionPerformed

    private void tMTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tMTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tMTelefonoActionPerformed

    private void tMDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tMDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tMDireccionActionPerformed

    private void tMPGanadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tMPGanadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tMPGanadosActionPerformed

    private void tMSueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tMSueldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tMSueldoActionPerformed

    private void tDDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tDDNIActionPerformed

    private void tDNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tDNombreActionPerformed

    private void tDTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tDTelefonoActionPerformed

    private void tDDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tDDireccionActionPerformed

    private void tDPGanadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDPGanadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tDPGanadosActionPerformed

    private void tDSueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDSueldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tDSueldoActionPerformed

    private void cDActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cDActivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cDActivoActionPerformed

    private void tEPlusPartidoGanadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tEPlusPartidoGanadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tEPlusPartidoGanadoActionPerformed

    private void tMPlusPartidoGanadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tMPlusPartidoGanadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tMPlusPartidoGanadoActionPerformed

    private void tJFechaNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tJFechaNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tJFechaNacimientoActionPerformed

    private void tEPlusPartidoGanado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tEPlusPartidoGanado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tEPlusPartidoGanado1ActionPerformed

    private void tJPlusPartidoGanadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tJPlusPartidoGanadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tJPlusPartidoGanadoActionPerformed

    private void tJNumeroGolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tJNumeroGolesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tJNumeroGolesActionPerformed

    private void tJPlusPorGolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tJPlusPorGolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tJPlusPorGolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bDefensa;
    private javax.swing.JRadioButton bDelantero;
    private javax.swing.JRadioButton bDelegado;
    private javax.swing.JRadioButton bPortero;
    private javax.swing.JRadioButton bPresidente;
    private javax.swing.JRadioButton bSecretario;
    private javax.swing.ButtonGroup bgCargoDirectivo;
    private javax.swing.ButtonGroup bgPosicion;
    private javax.swing.JCheckBox cDActivo;
    private javax.swing.JCheckBox cMFijo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lMPlusPartidoGanado;
    private javax.swing.JPanel pDirectivos;
    private javax.swing.JPanel pJugadores;
    private javax.swing.JPanel pMantenedores;
    private javax.swing.JTextField tDDNI;
    private javax.swing.JTextField tDDireccion;
    private javax.swing.JTextField tDNombre;
    private javax.swing.JTextField tDPGanados;
    private javax.swing.JTextField tDSueldo;
    private javax.swing.JTextField tDTelefono;
    private javax.swing.JTextField tEDNI;
    private javax.swing.JTextField tEDireccion;
    private javax.swing.JTextField tENombre;
    private javax.swing.JTextField tEPGanados;
    private javax.swing.JTextField tEPlusPartidoGanado;
    private javax.swing.JTextField tEPlusPartidoGanado1;
    private javax.swing.JTextField tESueldo;
    private javax.swing.JTextField tETelefono;
    private javax.swing.JTextField tJDNI;
    private javax.swing.JTextField tJDireccion;
    private javax.swing.JTextField tJFechaNacimiento;
    private javax.swing.JTextField tJNombre;
    private javax.swing.JTextField tJNumeroGoles;
    private javax.swing.JTextField tJPGanados;
    private javax.swing.JTextField tJPlusPartidoGanado;
    private javax.swing.JTextField tJPlusPorGol;
    private javax.swing.JTextField tJSueldo;
    private javax.swing.JTextField tJTelefono;
    private javax.swing.JTextField tMDNI;
    private javax.swing.JTextField tMDireccion;
    private javax.swing.JTextField tMNombre;
    private javax.swing.JTextField tMPGanados;
    private javax.swing.JTextField tMPlusPartidoGanado;
    private javax.swing.JTextField tMSueldo;
    private javax.swing.JTextField tMTelefono;
    private javax.swing.JPanel tpEntrenadores;
    private javax.swing.JTabbedPane tpGeneral;
    // End of variables declaration//GEN-END:variables
}
