package com.mycompany.ejercicio12_ajedrez;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.FocusEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author arube
 */
public class PanelCasilla extends javax.swing.JPanel {

    static java.awt.event.ActionEvent evtAnt = null;
    
    /**
     * Creates new form PanelCasilla
     */
    public PanelCasilla(Color colorFondo, String name) {
        initComponents();
        setBackground(colorFondo);
        setName(name);
        
        pieza.setBackground(null);
        
    }

    public void establecePieza(String nombrePieza) {
        Image originalImage = (new ImageIcon("piezas\\" + nombrePieza + ".png")).getImage();
        Image scaledImage = originalImage.getScaledInstance(38, 38, Image.SCALE_SMOOTH);
        pieza.setName(""+nombrePieza.charAt(nombrePieza.length()-1));
        
        pieza.setIcon(new ImageIcon(scaledImage));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pieza = new javax.swing.JButton();

        pieza.setBackground(new java.awt.Color(177, 177, 177));
        pieza.setBorderPainted(false);
        pieza.setFocusPainted(false);
        pieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piezaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pieza, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pieza, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void piezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piezaActionPerformed
        if(evtAnt != null){
            JButton bAnt = (JButton) evtAnt.getSource();
            JButton bnuevo = (JButton) evt.getSource();
            Icon moviento = bAnt.getIcon();
            String nombre = bAnt.getName();
            
            if(bnuevo.getName() != null && bnuevo.getName().equals(nombre)){
                evtAnt = null;
                return;
            }
            
            bAnt.setIcon(null);
            bAnt.setName("");
            
            if(bnuevo.getIcon() != null){
                PanelCementerio nuevoMuerto = new PanelCementerio();
                nuevoMuerto.establecePieza(bnuevo.getIcon());
                
                if (bnuevo.getName().equals("N"))
                    Ventana_Alberto.cementerioNegro.add(nuevoMuerto);
                
                else if (bnuevo.getName().equals("B"))
                    Ventana_Alberto.cementerioBlanco.add(nuevoMuerto);
                
            }
            
            bnuevo.setIcon(moviento);
            bnuevo.setName(nombre);
            
            evtAnt = null;
            
            Ventana_Alberto.estableceTurno();
        
        }else if(((JButton)evt.getSource()).getIcon() != null)
            if(Ventana_Alberto.turnoBlanco  && ((JButton) evt.getSource()).getName().equals("B") ||
               !Ventana_Alberto.turnoBlanco && ((JButton) evt.getSource()).getName().equals("N") )
                evtAnt = evt;
        
        
    }//GEN-LAST:event_piezaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton pieza;
    // End of variables declaration//GEN-END:variables
}
