/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ejercicio12_ajedrez;

import java.awt.Color;

/**
 *
 * @author arube
 */
public class Ventana_Alberto extends javax.swing.JFrame {

    public static boolean turnoBlanco = true;
    
    /**
     * Creates new form Ventana_Alberto
     */
    public Ventana_Alberto() {
        initComponents();
        layoutTablero.requestFocus();
        colocaPaneles();

    }
    
    public void colocaPaneles(){
        boolean empBlanco;
        
        for(int i = 8; i > 0; i--){
            if(i % 2 == 0) empBlanco = true;
            else           empBlanco = false;
            
            for(int j = 0; j < 8; j++){
                PanelCasilla panel = null;
                
                if(empBlanco){
                    panel = new PanelCasilla(Color.WHITE, ""+i+j);
                    empBlanco = false;
                
                }else{
                    panel = new PanelCasilla(Color.GRAY, ""+i+j);
                    empBlanco = true;
                }
                establecePieza(panel, i, j);
                layoutTablero.add(panel);
            }
        }
    }
    
    public void establecePieza(PanelCasilla panel, int i, int j){
        switch (i) {
            case 7:
                panel.establecePieza("peonN");
                break;
            case 2:
                panel.establecePieza("peonB");
                break;
            case 8:
                switch(j){
                    case 0, 7 -> {
                        panel.establecePieza("torreN");
                    }
                    case 1, 6 -> {
                        panel.establecePieza("caballoN");
                    }
                    case 2, 5 -> {
                        panel.establecePieza("alfilN");
                    }
                    case 3    -> {
                        panel.establecePieza("damaN");
                    }
                    case 4    -> {
                        panel.establecePieza("reyN");
                    }
                }   break;
            case 1:
                switch(j){
                    case 0, 7 -> {
                        panel.establecePieza("torreB");
                    }
                    case 1, 6 -> {
                        panel.establecePieza("caballoB");
                    }
                    case 2, 5 -> {
                        panel.establecePieza("alfilB");
                    }
                    case 3    -> {
                        panel.establecePieza("damaB");
                    }
                    case 4    -> {
                        panel.establecePieza("reyB");
                    }
                }   break;
            default:
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelNegro = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cementerioNegro = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        cementerioBlanco = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        labelBlanco = new javax.swing.JLabel();
        layoutTablero = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ajedrez Alberto");
        setResizable(false);

        labelNegro.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        labelNegro.setText("NEGRAS");
        labelNegro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 99, Short.MAX_VALUE)
                .addComponent(labelNegro, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(labelNegro, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setPreferredSize(new java.awt.Dimension(100, 400));

        cementerioNegro.setLayout(new java.awt.GridLayout(8, 2));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(cementerioNegro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cementerioNegro, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_END);

        cementerioBlanco.setLayout(new java.awt.GridLayout(8, 2));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(cementerioBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cementerioBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_START);

        jPanel4.setPreferredSize(new java.awt.Dimension(600, 100));

        labelBlanco.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        labelBlanco.setText("BLANCAS: VUESTRO TURNO");
        labelBlanco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 101, Short.MAX_VALUE)
                .addComponent(labelBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(labelBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_END);

        layoutTablero.setLayout(new java.awt.GridLayout(8, 8));
        getContentPane().add(layoutTablero, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel 
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Alberto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Alberto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Alberto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Alberto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        */
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Alberto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel cementerioBlanco;
    public static javax.swing.JPanel cementerioNegro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private static javax.swing.JLabel labelBlanco;
    private static javax.swing.JLabel labelNegro;
    private javax.swing.JPanel layoutTablero;
    // End of variables declaration//GEN-END:variables

    public static void estableceTurno(){
        if(turnoBlanco){
            turnoBlanco = false;
            labelNegro.setText("NEGRAS: VUESTRO TURNO");
            labelBlanco.setText("BLANCAS");
        }else{
            turnoBlanco = true;
            labelBlanco.setText("BLANCAS: VUESTRO TURNO");
            labelNegro.setText("NEGRAS");
        }
    }
}
