/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.mipaintedfilepanel;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author 6002754
 */
public class Interruptor extends javax.swing.JPanel {

    static private String keysPressed = "";
    CambiaColor cambiaColor = new CambiaColor();
    
    /**
     * Creates new form Interruptor
     */
    public Interruptor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        labelLuz = new javax.swing.JLabel();
        panelLuz = new javax.swing.JPanel();
        miPaintedFilePanel1 = new com.mycompany.mipaintedfilepanel.MiPaintedFilePanel();

        jToggleButton1.setText("Interruptor");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        labelLuz.setText("Apagado");

        javax.swing.GroupLayout panelLuzLayout = new javax.swing.GroupLayout(panelLuz);
        panelLuz.setLayout(panelLuzLayout);
        panelLuzLayout.setHorizontalGroup(
            panelLuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelLuzLayout.setVerticalGroup(
            panelLuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(labelLuz)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(panelLuz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelLuz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jToggleButton1)
                        .addGap(18, 18, 18)
                        .addComponent(labelLuz, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        miPaintedFilePanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miPaintedFilePanel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                miPaintedFilePanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                miPaintedFilePanel1MouseExited(evt);
            }
        });
        miPaintedFilePanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                miPaintedFilePanel1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout miPaintedFilePanel1Layout = new javax.swing.GroupLayout(miPaintedFilePanel1);
        miPaintedFilePanel1.setLayout(miPaintedFilePanel1Layout);
        miPaintedFilePanel1Layout.setHorizontalGroup(
            miPaintedFilePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        miPaintedFilePanel1Layout.setVerticalGroup(
            miPaintedFilePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(miPaintedFilePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(miPaintedFilePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if (!jToggleButton1.isSelected()) {
            labelLuz.setText("Apagado");
            panelLuz.setBackground(null);
        } else {
            labelLuz.setText("Encendido");
            panelLuz.setBackground(Color.YELLOW);
        }

    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void miPaintedFilePanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miPaintedFilePanel1MouseEntered
        JPanel panel = (JPanel) evt.getSource();
        panel.setBackground(Color.CYAN);
    }//GEN-LAST:event_miPaintedFilePanel1MouseEntered

    private void miPaintedFilePanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miPaintedFilePanel1MouseExited
        JPanel panel = (JPanel) evt.getSource();
        panel.setBackground(null);
    }//GEN-LAST:event_miPaintedFilePanel1MouseExited

    private void miPaintedFilePanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miPaintedFilePanel1MouseClicked
        //MiPaintedFilePanel panel = (MiPaintedFilePanel) evt.getSource();
        //panel.setRutaImg;
    }//GEN-LAST:event_miPaintedFilePanel1MouseClicked

    private void miPaintedFilePanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_miPaintedFilePanel1KeyPressed
        keysPressed += evt.getKeyChar();
        
        if(cambiaColor== null && keysPressed.contains("arcoiris")){
            cambiaColor.run();
        }
    }//GEN-LAST:event_miPaintedFilePanel1KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel labelLuz;
    private static com.mycompany.mipaintedfilepanel.MiPaintedFilePanel miPaintedFilePanel1;
    private javax.swing.JPanel panelLuz;
    // End of variables declaration//GEN-END:variables


    class CambiaColor extends Thread{

        @Override
        public void run() {
            while(true){
                miPaintedFilePanel1.setBackground(Color.RED);
                miPaintedFilePanel1.setBackground(Color.BLUE);
                miPaintedFilePanel1.setBackground(Color.MAGENTA);
                miPaintedFilePanel1.setBackground(Color.GREEN);
                miPaintedFilePanel1.setBackground(Color.YELLOW);
                miPaintedFilePanel1.setBackground(Color.CYAN);
            }
        }
        
    }
}
