/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.mipaintedfilepanel;

import java.awt.Graphics;
import java.io.File;
import javax.swing.ImageIcon;

/**
 *
 * @author 6002754
 */
public class MiPaintedFilePanel extends javax.swing.JPanel {

    private File rutaImg;
    
    public MiPaintedFilePanel() {
        initComponents();
    }

    public File getRutaImg() {
        return rutaImg;
    }

    public void setRutaImg(File rutaImg) {
        this.rutaImg = rutaImg;
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        if(rutaImg != null && rutaImg.exists()){
            ImageIcon imagen = new ImageIcon(rutaImg.getPath());
            g.drawImage(imagen.getImage(), 0, 0, null);
        }
        
    }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
