/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.inmobiliaria_alberto;

import java.awt.Color;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.text.SimpleDateFormat;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author 6002754
 */
public class VentanaMain extends javax.swing.JFrame {

    //Creamos el modelo del jList
    DefaultListModel modelo;
    
    //Creamos la ventana de información pero invisible
    DialogInfo ventanaInfo = new DialogInfo(null, false);
    /**
     * Creates new form VentanaMain
     */
    public VentanaMain() {
        initComponents();
        
        //Establecemos el modelo a la tabla
        modelo = new DefaultListModel<>();
        areaMuestra.setModel(modelo);
        
        //Ponemos el icono del botón de información
        tbInfo.setIcon(new ImageIcon("botonInfo.jpg"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTipo = new javax.swing.ButtonGroup();
        panelDatos = new javax.swing.JPanel();
        tNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tNIF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tRazonSocial = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tComision = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tInquilino = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tPropietario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        listaEmpleado = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        tDescripcion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tPrecio = new javax.swing.JTextField();
        tDescuento = new javax.swing.JTextField();
        rbOtro = new javax.swing.JRadioButton();
        rbMes = new javax.swing.JRadioButton();
        rbSemana = new javax.swing.JRadioButton();
        rbDia = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        tFecha = new javax.swing.JSpinner();
        tbInfo = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaMuestra = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiGrabar = new javax.swing.JMenuItem();
        jmiBorrar = new javax.swing.JMenuItem();
        jmiCambiarColor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiImportar = new javax.swing.JMenuItem();
        jmiExportar = new javax.swing.JMenuItem();
        jmSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tNombreFocusLost(evt);
            }
        });
        tNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNombreActionPerformed(evt);
            }
        });
        tNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tNombreKeyPressed(evt);
            }
        });

        jLabel1.setText("Nombre:");

        jLabel2.setText("NIF:");

        tNIF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tNIFFocusLost(evt);
            }
        });
        tNIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNIFActionPerformed(evt);
            }
        });
        tNIF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tNIFKeyPressed(evt);
            }
        });

        jLabel3.setText("Razón Social:");

        tRazonSocial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tRazonSocialFocusLost(evt);
            }
        });
        tRazonSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tRazonSocialActionPerformed(evt);
            }
        });
        tRazonSocial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tRazonSocialKeyPressed(evt);
            }
        });

        jLabel4.setText("Comisión:");

        tComision.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tComisionFocusLost(evt);
            }
        });
        tComision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tComisionActionPerformed(evt);
            }
        });
        tComision.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tComisionKeyPressed(evt);
            }
        });

        jLabel8.setText("Inquilino");

        tInquilino.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tInquilinoFocusLost(evt);
            }
        });
        tInquilino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tInquilinoActionPerformed(evt);
            }
        });
        tInquilino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tInquilinoKeyPressed(evt);
            }
        });

        jLabel7.setText("Propietario");

        tPropietario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tPropietarioFocusLost(evt);
            }
        });
        tPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPropietarioActionPerformed(evt);
            }
        });
        tPropietario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tPropietarioKeyPressed(evt);
            }
        });

        jLabel6.setText("Empleados");

        listaEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alberto", "Mia", "Carro", "Adrián", "Achraf", "Renzo", "David", "Victor", "Yiawei", "Curto" }));

        jLabel5.setText("Descripción");

        tDescripcion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tDescripcionFocusLost(evt);
            }
        });
        tDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDescripcionActionPerformed(evt);
            }
        });
        tDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tDescripcionKeyPressed(evt);
            }
        });

        jLabel10.setText("Descuento:");

        jLabel9.setText("Precio:");

        tPrecio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tPrecioFocusLost(evt);
            }
        });
        tPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPrecioActionPerformed(evt);
            }
        });
        tPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tPrecioKeyPressed(evt);
            }
        });

        tDescuento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tDescuentoFocusLost(evt);
            }
        });
        tDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDescuentoActionPerformed(evt);
            }
        });
        tDescuento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tDescuentoKeyPressed(evt);
            }
        });

        grupoTipo.add(rbOtro);
        rbOtro.setText("Otro");
        rbOtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOtroActionPerformed(evt);
            }
        });

        grupoTipo.add(rbMes);
        rbMes.setText("Mes");
        rbMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMesActionPerformed(evt);
            }
        });

        grupoTipo.add(rbSemana);
        rbSemana.setText("Semana");
        rbSemana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSemanaActionPerformed(evt);
            }
        });

        grupoTipo.add(rbDia);
        rbDia.setText("Día");
        rbDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDiaActionPerformed(evt);
            }
        });

        jLabel28.setText("Fecha");

        tFecha.setModel(new javax.swing.SpinnerDateModel());

        tbInfo.setText("INFO");
        tbInfo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tbInfo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tbInfoStateChanged(evt);
            }
        });
        tbInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(18, 18, 18)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tNIF, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tComision, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tbInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(rbOtro, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(tDescuento))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosLayout.createSequentialGroup()
                        .addComponent(rbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(tPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbSemana, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbDia, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7)
                                .addGroup(panelDatosLayout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(jLabel8))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listaEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tPropietario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tInquilino, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addComponent(rbDia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbSemana))
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbMes)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbOtro)
                            .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(listaEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addComponent(tRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44))
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tNIF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tComision, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tbInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(areaMuestra);

        jMenu1.setText("Archivo");

        jmiGrabar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiGrabar.setIcon(new ImageIcon("grabar.png"));
        jmiGrabar.setText("Grabar");
        jmiGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGrabarActionPerformed(evt);
            }
        });
        jMenu1.add(jmiGrabar);

        jmiBorrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiBorrar.setIcon(new ImageIcon("borrar.png"));
        jmiBorrar.setText("Borrar línea");
        jmiBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBorrarActionPerformed(evt);
            }
        });
        jMenu1.add(jmiBorrar);

        jmiCambiarColor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiCambiarColor.setIcon(new ImageIcon("rgb.png"));
        jmiCambiarColor.setText("Cambiar color");
        jmiCambiarColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCambiarColorActionPerformed(evt);
            }
        });
        jMenu1.add(jmiCambiarColor);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("E / S Archivos");

        jmiImportar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiImportar.setIcon(new ImageIcon("importar.png"));
        jmiImportar.setText("Importar");
        jmiImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiImportarActionPerformed(evt);
            }
        });
        jMenu2.add(jmiImportar);

        jmiExportar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiExportar.setIcon(new ImageIcon("exportar.png"));
        jmiExportar.setText("Exportar");
        jmiExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiExportarActionPerformed(evt);
            }
        });
        jMenu2.add(jmiExportar);

        jMenuBar1.add(jMenu2);

        jmSalir.setIcon(new ImageIcon("salir.png"));
        jmSalir.setMnemonic('S');
        jmSalir.setText("Salir");
        jmSalir.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jmSalirMenuSelected(evt);
            }
        });
        jmSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmSalirMouseClicked(evt);
            }
        });
        jmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(jmSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(panelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNombreActionPerformed

    private void tNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNombreKeyPressed
        //Al pulsar una tecla ponemos el color en negro, para quitar el rojo en caso de que hubiese estado mal
        ((JTextField)evt.getSource()).setForeground(Color.BLACK);
    }//GEN-LAST:event_tNombreKeyPressed

    private void tNIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNIFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNIFActionPerformed

    private void tNIFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNIFKeyPressed
        //Al pulsar una tecla ponemos el color en negro, para quitar el rojo en caso de que hubiese estado mal
        ((JTextField)evt.getSource()).setForeground(Color.BLACK);
    }//GEN-LAST:event_tNIFKeyPressed

    private void tRazonSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tRazonSocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tRazonSocialActionPerformed

    private void tRazonSocialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tRazonSocialKeyPressed
        //Al pulsar una tecla ponemos el color en negro, para quitar el rojo en caso de que hubiese estado mal
        ((JTextField)evt.getSource()).setForeground(Color.BLACK);
    }//GEN-LAST:event_tRazonSocialKeyPressed

    private void tComisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tComisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tComisionActionPerformed

    private void tComisionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tComisionKeyPressed
        //Al pulsar una tecla ponemos el color en negro, para quitar el rojo en caso de que hubiese estado mal
        ((JTextField)evt.getSource()).setForeground(Color.BLACK);
    }//GEN-LAST:event_tComisionKeyPressed

    private void jmiGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGrabarActionPerformed
        try{
            
            //Comprobamos que todos los campos TextField estñan rellenos
            
            if(!compruebaCampoVacio(tNombre, "Nombre") ||
           !compruebaCampoVacio(tRazonSocial, "NIF") ||
           !compruebaCampoVacio(tNIF, "Razón Social") ||
           !compruebaCampoVacio(tComision, "Comisión") ||
           !compruebaCampoVacio(tDescripcion, "Descripción") ||
           !compruebaCampoVacio(tPropietario, "Propietario") ||
           !compruebaCampoVacio( tInquilino, "Inquilino") ||
           !compruebaCampoVacio(tPrecio, "Precio") ||
           !compruebaCampoVacio(tDescuento, "Descuento"))
                return;
            
            //Comprobamos que hay una opción de tipo marcada y la recogemos en "tipo"
            String tipo = "";
            if (grupoTipo.getSelection() == rbDia.getModel()) tipo = "Día";
            else if (grupoTipo.getSelection() == rbSemana.getModel()) tipo = "Semana";
            else if (grupoTipo.getSelection() == rbMes.getModel()) tipo = "Mes";
            else if (grupoTipo.getSelection() == rbOtro.getModel()) tipo = "Otro";
            else {
                //Si no había nada, mostramos el aviso y marcamos el primer botón
                JOptionPane.showMessageDialog(this, "No has seleccionado el tipo ", "Campo vacío", JOptionPane.ERROR_MESSAGE);
                rbDia.requestFocus();
                return;
            }
            //Creamos el forateador para la fecha
            SimpleDateFormat sdf = new SimpleDateFormat("dd/mm/yyyy");
            
            //Instanciamos la operación con los datos recabados
            Operaciones nuevaOpera = new Operaciones(tipo, tDescripcion.getText(), listaEmpleado.getSelectedItem().toString(), 
                    tPropietario.getText(), tInquilino.getText(), sdf.format(tFecha.getValue()), 
                    Double.parseDouble(tPrecio.getText()), Double.parseDouble(tDescuento.getText()), tNombre.getText(), 
                    tRazonSocial.getText(), tNIF.getText(), Double.parseDouble(tComision.getText()));

            //Añadimos los datos a la lista, enviando solo los que marcaba el enunciado del examen
            modelo.addElement(nuevaOpera.filaToList());
            
            //Borramos toda la información que hubiese marcada
            tNombre.setText("");
            tRazonSocial.setText("");
            tNIF.setText("");
            tComision.setText("");
            tDescripcion.setText("");
            tPropietario.setText("");
            tInquilino.setText("");
            tPrecio.setText("");
            tDescuento.setText("");
            rbSemana.setSelected(false);
            rbDia.setSelected(false);
            rbMes.setSelected(false);
            rbOtro.setSelected(false);
            listaEmpleado.setSelectedIndex(0);
            
        }catch(Exception e){
            //Esta expeción es solo para casos donde se hayan burlado las comprobaciones, generalmente tipos de datos
            System.err.println(e.getMessage());
            JOptionPane.showMessageDialog(this, "Alguno de los campos introducidos no tiene un formato válido. Probablemente será un valor numérico", "Error de formato", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jmiGrabarActionPerformed

    private void jmiBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBorrarActionPerformed
        //En función d ela linea marcada, se borra la fila del modelo y se avisa al usuario
        if(areaMuestra.getSelectedIndex() != -1){
            modelo.removeElementAt(areaMuestra.getSelectedIndex());
            JOptionPane.showMessageDialog(this, "Fila borrada correctamente", "Confirmación", JOptionPane.INFORMATION_MESSAGE);
        }else
            JOptionPane.showMessageDialog(this, "No has seleccionado ninguna línea para borrar", "Error de selección en la lista", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jmiBorrarActionPerformed

    private void jmiCambiarColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCambiarColorActionPerformed
        //Linea para cambiar el color del panel
        panelDatos.setBackground(JColorChooser.showDialog(this, "Elige el color del panel principal", Color.yellow));
        
    }//GEN-LAST:event_jmiCambiarColorActionPerformed

    private void jmiImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiImportarActionPerformed
        //Codigo para importar datos de un fichero
        String cadena = "";

        //Elegimos el fichero
        JFileChooser fc = new JFileChooser();
        int i = fc.showOpenDialog(this);
        
        //En función del fichero elegido pasamos a leerlo
        if(i==JFileChooser.APPROVE_OPTION){
            File fichero = fc.getSelectedFile();
                
            //Vamos leyendo y almacenando en cadenas todo lo que se haya escrito
            try(FileReader fr = new FileReader(fichero)){
                int valor = fr.read();
                while(valor!=-1){
                    cadena+=(char)valor;
                    valor = fr.read();
                }
                
                //Eliminamos caracteres que no nos combienen
                cadena = cadena.replaceAll(", ", "\n");
                cadena = cadena.replaceAll("\\[", "");
                cadena = cadena.replaceAll("\\]", "");

            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Error en la lectura de los datos", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        //Ponemos el modelo en vacío
        modelo.removeAllElements();

        //Separamos lo leido en filas
        String[] cadenas = cadena.split("\n");

        //Las añadimos al modelo de una en una
        for(int j=0; j < cadenas.length; j++)
            modelo.addElement(cadenas[j]);
    }//GEN-LAST:event_jmiImportarActionPerformed

    private void jmiExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiExportarActionPerformed
        //Pedimos un fichero donde importar
        JFileChooser fc = new JFileChooser();
        int i = fc.showOpenDialog(this);
        
        if(i==JFileChooser.APPROVE_OPTION){
            File fichero = fc.getSelectedFile();
            
            //Escribimos el objeto modelo directamente sobre el archivo y avisamos al usuario de ello
            try(FileWriter fw = new FileWriter(fichero)){
                
                fw.write(modelo.toString());
                            
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Error en la escritura de los datos", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        JOptionPane.showMessageDialog(this, "Datos escritos correctamente", "Confirmación", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jmiExportarActionPerformed

    private void jmSalirMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jmSalirMenuSelected
        //En función de la elección del usuario, se pasará o no por el exit
        int i = JOptionPane.showConfirmDialog(this, "¿Seguro que desea salir?", "SALIR", JOptionPane.YES_NO_OPTION);
        if(i == JOptionPane.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_jmSalirMenuSelected

    private void jmSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmSalirMouseClicked
        
    }//GEN-LAST:event_jmSalirMouseClicked

    private void jmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSalirActionPerformed

    }//GEN-LAST:event_jmSalirActionPerformed

    private void tDescuentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tDescuentoKeyPressed
        //Ponemos el color a negro para quitar el rojo si pasó por un error
        ((JTextField)evt.getSource()).setForeground(Color.BLACK);
    }//GEN-LAST:event_tDescuentoKeyPressed

    private void tDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tDescuentoActionPerformed

    private void tPrecioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tPrecioKeyPressed
        //Ponemos el color a negro para quitar el rojo si pasó por un error
        ((JTextField)evt.getSource()).setForeground(Color.BLACK);
    }//GEN-LAST:event_tPrecioKeyPressed

    private void tPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPrecioActionPerformed

    private void tInquilinoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tInquilinoKeyPressed
        //Ponemos el color a negro para quitar el rojo si pasó por un error
        ((JTextField)evt.getSource()).setForeground(Color.BLACK);
    }//GEN-LAST:event_tInquilinoKeyPressed

    private void tInquilinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tInquilinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tInquilinoActionPerformed

    private void tPropietarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tPropietarioKeyPressed
        //Ponemos el color a negro para quitar el rojo si pasó por un error
        ((JTextField)evt.getSource()).setForeground(Color.BLACK);
    }//GEN-LAST:event_tPropietarioKeyPressed

    private void tPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPropietarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPropietarioActionPerformed

    private void tDescripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tDescripcionKeyPressed
        //Ponemos el color a negro para quitar el rojo si pasó por un error
        ((JTextField)evt.getSource()).setForeground(Color.BLACK);
    }//GEN-LAST:event_tDescripcionKeyPressed

    private void tDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tDescripcionActionPerformed

    private void rbOtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOtroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbOtroActionPerformed

    private void rbMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMesActionPerformed

    private void rbSemanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSemanaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSemanaActionPerformed

    private void rbDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbDiaActionPerformed

    private void tNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tNombreFocusLost
        //Comprobamos que el campo es correcto y si no lo ponemos a rojo y le dmaos el foco
        if(!compruebaCampoVacio(((JTextField)evt.getSource()), "Nombre")){
            ((JTextField)evt.getSource()).requestFocus();
        }       
    }//GEN-LAST:event_tNombreFocusLost

    private void tNIFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tNIFFocusLost
        //Comprobamos que el campo es correcto y si no lo ponemos a rojo y le dmaos el foco
        if(!compruebaCampoVacio(((JTextField)evt.getSource()), "NIF")){
            ((JTextField)evt.getSource()).requestFocus();
        }  
    }//GEN-LAST:event_tNIFFocusLost

    private void tRazonSocialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tRazonSocialFocusLost
        //Comprobamos que el campo es correcto y si no lo ponemos a rojo y le dmaos el foco
        if(!compruebaCampoVacio(((JTextField)evt.getSource()), "Razón Social")){
            ((JTextField)evt.getSource()).requestFocus();
        }  
    }//GEN-LAST:event_tRazonSocialFocusLost

    private void tComisionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tComisionFocusLost
        //Comprobamos que el campo es correcto y si no lo ponemos a rojo y le dmaos el foco
        if(!compruebaCampoVacio(((JTextField)evt.getSource()), "Comisión")){
            ((JTextField)evt.getSource()).requestFocus();
            
        } else {
            try{
                Double.parseDouble(((JTextField)evt.getSource()).getText());
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "El campo debe contener solo números o números decimales", "Campo vacío", JOptionPane.ERROR_MESSAGE);
                ((JTextField)evt.getSource()).requestFocus();
            }
        }
    }//GEN-LAST:event_tComisionFocusLost

    private void tDescuentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tDescuentoFocusLost
        //Comprobamos que el campo es correcto y si no lo ponemos a rojo y le dmaos el foco
        if(!compruebaCampoVacio(((JTextField)evt.getSource()), "Descuento")){
            ((JTextField)evt.getSource()).requestFocus();
            
        } else {
            try{
                Double.parseDouble(((JTextField)evt.getSource()).getText());
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "El campo debe contener solo números o números decimales", "Campo vacío", JOptionPane.ERROR_MESSAGE);
                ((JTextField)evt.getSource()).requestFocus();
            }
        }
    }//GEN-LAST:event_tDescuentoFocusLost

    private void tPrecioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tPrecioFocusLost
        //Comprobamos que el campo es correcto y si no lo ponemos a rojo y le dmaos el foco
        if(!compruebaCampoVacio(((JTextField)evt.getSource()), "Precio")){
            ((JTextField)evt.getSource()).requestFocus();
            
        } else {
            try{
                Double.parseDouble(((JTextField)evt.getSource()).getText());
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "El campo debe contener solo números o números decimales", "Campo vacío", JOptionPane.ERROR_MESSAGE);
                ((JTextField)evt.getSource()).requestFocus();
            }
        }
    }//GEN-LAST:event_tPrecioFocusLost

    private void tDescripcionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tDescripcionFocusLost
        //Comprobamos que el campo es correcto y si no lo ponemos a rojo y le dmaos el foco
        if(!compruebaCampoVacio(((JTextField)evt.getSource()), "Precio")){
            ((JTextField)evt.getSource()).requestFocus();
            
        }
    }//GEN-LAST:event_tDescripcionFocusLost

    private void tPropietarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tPropietarioFocusLost
        //Comprobamos que el campo es correcto y si no lo ponemos a rojo y le dmaos el foco
        if(!compruebaCampoVacio(((JTextField)evt.getSource()), "Precio")){
            ((JTextField)evt.getSource()).requestFocus();
            
        }
    }//GEN-LAST:event_tPropietarioFocusLost

    private void tInquilinoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tInquilinoFocusLost
        //Comprobamos que el campo es correcto y si no lo ponemos a rojo y le dmaos el foco
        if(!compruebaCampoVacio(((JTextField)evt.getSource()), "Precio")){
            ((JTextField)evt.getSource()).requestFocus();
            
        }
    }//GEN-LAST:event_tInquilinoFocusLost

    private void tbInfoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tbInfoStateChanged
        //Si el botón está activado se muestra el Dialog y si no se quita
        if(tbInfo.isSelected())
            ventanaInfo.setVisible(true);
        else
            ventanaInfo.setVisible(false);
        
            
    }//GEN-LAST:event_tbInfoStateChanged

    private void tbInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> areaMuestra;
    private javax.swing.ButtonGroup grupoTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu jmSalir;
    private javax.swing.JMenuItem jmiBorrar;
    private javax.swing.JMenuItem jmiCambiarColor;
    private javax.swing.JMenuItem jmiExportar;
    private javax.swing.JMenuItem jmiGrabar;
    private javax.swing.JMenuItem jmiImportar;
    private javax.swing.JComboBox<String> listaEmpleado;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JRadioButton rbDia;
    private javax.swing.JRadioButton rbMes;
    private javax.swing.JRadioButton rbOtro;
    private javax.swing.JRadioButton rbSemana;
    private javax.swing.JTextField tComision;
    private javax.swing.JTextField tDescripcion;
    private javax.swing.JTextField tDescuento;
    private javax.swing.JSpinner tFecha;
    private javax.swing.JTextField tInquilino;
    private javax.swing.JTextField tNIF;
    private javax.swing.JTextField tNombre;
    private javax.swing.JTextField tPrecio;
    private javax.swing.JTextField tPropietario;
    private javax.swing.JTextField tRazonSocial;
    private javax.swing.JToggleButton tbInfo;
    // End of variables declaration//GEN-END:variables

    private boolean compruebaCampoVacio(JTextField textField, String nombreCampo) {
        
        //Con este método se comprueba si el campo recibido está vacío, si es el caso, se pone el texto en rojo y se le da el foco
        if(textField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "El campo "+ nombreCampo + " está vacío", "Campo vacío", JOptionPane.ERROR_MESSAGE);
            textField.requestFocus();
            textField.setForeground(Color.red);
            return false;

        }else
            //En otro caso, se devuelve true
            return true;
        }
}
