/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */


import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author 6002754
 */
public class DialogListas extends javax.swing.JDialog {

    DefaultListModel modelo;
    
    /**
     * Creates new form DialogVentana2
     */
    public DialogListas(java.awt.Frame parent, boolean modal, ArrayList<Coche> mostrar) {
        super(parent, modal);
        initComponents();
        modelo = new DefaultListModel();
        muestraCoches.setModel(modelo);
        
        for(Coche c: mostrar)
            modelo.addElement(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        muestraCoches = new javax.swing.JList<>();

        setTitle("Datos del cliente");

        jScrollPane2.setViewportView(muestraCoches);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(726, 179));
    }// </editor-fold>//GEN-END:initComponents

    public void actualizaLista(ArrayList<Coche> coches){
        modelo = new DefaultListModel();
        for(Coche c: coches)
            modelo.addElement(c);
        
        muestraCoches.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> muestraCoches;
    // End of variables declaration//GEN-END:variables
}
